services:
  beer-app:
    image: ghcr.io/itsmebrille/nakabeer:latest  # Use lowercase!
    container_name: beer-counter
    ports:
      - "80:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/beer_logs.db
