name: Docker Image CI  # ✅ Required: Name of the workflow

on:  # ✅ Required: Define when the workflow runs
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  # ✅ Required: Define at least one job
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image to GHCR
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/nakabeer:latest
          docker build . -f Dockerfile -t $IMAGE_NAME
          docker push $IMAGE_NAME
