name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write  # Required to push to GHCR
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/nakabeer:latest
        docker build . -f Dockerfile -t $IMAGE_NAME
        docker push $IMAGE_NAME
